### ISSUE TITLE
Now only the first time is i18n

### ISSUE THREAD

**Issue by yk0n9** [longbridgeapp/rust-i18n#87]
my code:
```rust
rust_i18n::i18n!("locales");

fn main() {
    rust_i18n::set_locale("zh-CN");
    for _ in 0..5 {
        show_message(t!("ok"), t!("hello"));
        thread::sleep(Duration::from_secs(1));
    }
}

fn show_message(title: impl AsRef<str>, message: impl AsRef<str>) {
    rfd::MessageDialog::new()
        .set_title(title.as_ref())
        .set_description(message.as_ref())
        .show();
}
```
zh-CN.yaml
```yaml
ok: "好的"
hello: "你好 世界"
```
en-US.yaml
```yaml
ok: "OK"
hello: "Hello World"
```
***first time***
![image](https://github.com/user-attachments/assets/7e5688d9-d7a6-493d-9d73-198386089495)
***second time***
![image](https://github.com/user-attachments/assets/f76e1025-a7e1-4818-a974-994853947854)

It can be found that even the first call will not be fully ```i18n```
The second or subsequent calls will never find the yaml content

**Comment by yk0n9** [comment]
rustc 1.80.1
rust-i18n 3.1.1

**Comment by KKRainbow** [comment]
this issue is casued by following path:

1. I18nConfig has a default value "en" on default_locale
2. lib.rs: load_metadata will use this default value when init Args. which make Args::default_locale always be Some("xxx")
3. when default_locale is Some(x), the rust_i18n::i18n! macro always call `rust_i18n::set_locale(#default_locale);` during init _RUST_I18N_BACKEND.
4. _RUST_I18N_BACKEND is lazily inited until the first call of t!() macro, and overwrite original value set by rust_i18n::set_locale.

for a workaround, just call t!() before set_locale.

for bugfix, i think when init default_locale, should check if set_locale is already called.
